uint8 BASE=0
uint8 WORK=1
uint8 TOOL=2
uint8 reference_type
string reference_name
---
bool success
int32 api2_status
float64[6] current_joint_degrees
float64[3] pose_position_m
float64[4] pose_quaternion_wxyz
string message
